baseURL = "https://index.kwon.nyc/"
languageCode = "en-us"
title = "index.kwon.nyc"

# Disable Hugo features we don't need
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params]
  description = "every page in my kwon(dot) ecosystem"

[module]
  # Disable theme/module lookup entirely
  disable = true